typedef struct avioes {
	int x;
	int y;
	int velocidade;
	int combustivel;
	int placar;
} AVIOES;
typedef struct destinos {
	char *nome;
	int localizacao_x;
	int localizacao_y;
	int dificuldade;
	int sorteio;
} DESTINOS;

void iniciaDestinos(DESTINOS paises[]) {
	/*//Dificuldade 1
	DESTINOS canada;
		canada.nome = "Canadá";
		canada.localizacao_x = x;	
		canada.localizacao_y = y;
		canada.dificuldade = 1;
		canada.sorteio = 1;
	DESTINOS eua;
		eua.nome = "Estados Unidos da Améica";
		eua.localizacao_x = x;
		eua.localizacao_y = y;
		eua.dificuldade = 1;
		eua.sorteio = 2;
	DESTINOS mexico;
		mexico.nome = "México";
		mexico.localizacao_x = x;
		mexico.localizacao_y = y;
		mexico.dificuldade = 1;
		mexico.sorteio = 3;
	DESTINOS caribe;
		caribe.nome = "Caribe";
		caribe.localizacao_x = x;
		caribe.localizacao_y = y;
		caribe.dificuldade = 1;
		caribe.sorteio = 4;
	DESTINOS portoRico;
		portoRico.nome = "Porto Rico";
		portoRico.localizacao_x = x;
		portoRico.localizacao_y = y;
		portoRico.dificuldade = 1;
		portoRico.sorteio = 5;
	DESTINOS costaRica;
		costaRica.nome = "Costa Rica";
		costaRica.localizacao_x = x;
		costaRica.localizacao_y = y;
		costaRica.dificuldade = 1;
		costaRica.sorteio = 6;
	DESTINOS honduras;
		honduras.nome = "Honduras";
		honduras.localizacao_x = x;
		honduras.localizacao_y = y;
		honduras.dificuldade = 1;
		honduras.sorteio = 7;
	DESTINOS argentina;
		argentina.nome = "Argentina";
		argentina.localizacao_x = x;
		argentina.localizacao_y = y;
		argentina.dificuldade = 1;
		argentina.sorteio = 8;
	DESTINOS bolivia;
		bolivia.nome = "Bolívia";
		bolivia.localizacao_x = x;
		bolivia.localizacao_y = y;
		bolivia.dificuldade = 1;
		bolivia.sorteio = 9;
	DESTINOS brasil;
		brasil.nome = "Brasil";
		brasil.localizacao_x = x;
		brasil.localizacao_y = y;
		brasil.dificuldade = 1;
		brasil.sorteio = 10;
	DESTINOS chile;
		chile.nome = "Chile";
		chile.localizacao_x = x;
		chile.localizacao_y = y;
		chile.dificuldade = 1;
		chile.sorteio = 11;
	DESTINOS colombia;
		colombia.nome = "Colômbia";
		colombia.localizacao_x = x;
		colombia.localizacao_y = y;
		colombia.dificuldade = 1;
		colombia.sorteio = 12;
	DESTINOS equador;
		equador.nome = "Equador";
		equador.localizacao_x = x;
		equador.localizacao_y = y;
		equador.dificuldade = 1;
		equador.sorteio = 13;
	DESTINOS paraguai;
		paraguai.nome = "Paraguai";
		paraguai.localizacao_x = x;
		paraguai.localizacao_y = y;
		paraguai.dificuldade = 1;
		paraguai.sorteio = 14;
	DESTINOS peru;
		peru.nome = "Peru";
		peru.localizacao_x = x;
		peru.localizacao_y = y;
		peru.dificuldade = 1;
		peru.dificuldade = 15;
	DESTINOS uruguai;
		uruguai.nome = "Uruguai";
		uruguai.localizacao_x = x;
		uruguai.localizacao_y = y;
		uruguai.dificuldade = 1;
		uruguai.sorteio = 16;
	DESTINOS venezuela;
		venezuela.nome = "Venezuela";
		venezuela.localizacao_x = x;
		venezuela.localizacao_y = y;
		venezuela.dificuldade = 1;
		venezuela.sorteio = 17;
	DETINOS africaSul;
		africaSul.nome = "África do Sul";
		africaSul.localizacao_x = x;
		africaSul.localizacao_y = y;
		africaSul.dificuldade = 1;
		africaSul.sorteio = 18;
	DESTINOS camaroes;
		camaroes.nome = "Camarões";
		camaroes.localizacao_x = x;
		camaroes.localizacao_y = y;
		camaroes.dificuldade = 1;
		camaroes.sorteio = 19;
	DESTINOS costaMarfim;
		costaMarfim.nome = "Costa do Marfim";
		costaMarfim.localizacao_x = x;
		costaMarfim.localizacao_y = y;
		costaMarfim.dificuldade = 1;
		costaMarfim.sorteio = 20;
	DESTINOS egito;
		egito.nome = "Egito";
		egito.localizacao_x = x;
		egito.localizacao_y = y;
		egito.dificuldade = 1;
		egito.sorteio = 21;
	DESTINOS gana;
		gana.nome = "Gana";
		gana.localizacao_x = x;
		gana.localizacao_y = y;
		gana.dificuldade = 1;
		gana.sorteio = 22;
	DESTINOS libia;
		libia.nome = "Líbia";
		libia.localizacao_x = x;
		libia.localizacao_y = y;
		libia.dificuldade = 1;
		libia.sorteio = 23;
	DESTINOS madagascar;
		madagascar.nome = "Madagáscar";
		madagascar.localizacao_x = x;
		madagascar.localizacao_y = y;
		madagascar.dificuldade = 1;
		madagascar.sorteio = 24;
	DESTINOS marrocos;
		marrocos.nome = "Marrocos";
		marrocos.localizacao_x = x;
		marrocos.localizacao_y = y;
		marrocoes.dificuldade = 1;
		marrocoes.sorteio = 25;
	DESTINOS mocambique;
		mocambique.nome = "Moçambique";
		mocambique.localizacao_x = x;
		mocambique.localizacao_y = y;
		mocambique.dificuldade = 1;
		mocambique.sorteio = 26;
	DESTINOS nigeria;
		nigeria.nome = "Nigéria";
		nigeria.localizacao_x = x;
		nigeria.localizacao_y = y;
		nigeria.dificuldade = 1;
		nigeria.sorteio = 27;
	DESTINOS senegal;
		senegal.nome = "Senegal";
		senegal.localizacao_x = x;
		senegal.localizacao_y = y;
		senegal.dificuldade = 1;
		senegal.sorteio = 28;
	DESTINOS somalia;
		somalia.nome = "Somália";
		somalia.localizacao_x = x;
		somalia.localizacao_y = y;
		somalia.dificuldade = 1;
		somalia.sorteio = 29;
	DESTINOS australia = { "Austrália", x, y, 1, 30 };
	DESTINOS novaZelandia = { "Nova Zelândia", x, y, 1, 31 };
	DESTINOS arabiaSaudita = { "Arábia Saudita", x, y, 1, 32 };
	DESTINOS bangladesh = { "Bangladesh", x, y, 1, 33 };
	DESTINOS cazaquistao = { "Cazaquistão", x, y, 1, 34 };
	DESTINOS coreiaNorte = { "Coréia do Norte", x, y, 1, 35 };
	DESTINOS coreiaSul = { "Coréia do Sul", x, y, 1, 36 };
	DESTINOS indonesia = { "Indonésia", x, y, 1, 37 };
	DESTINOS india = { "Índia", x, y, 1, 38 };
	DESTINOS ira = { "Irã", x, y, 1, 39 };
	DESTINOS iraque = { "Iraque", x, y, 1, 40 };
	DESTINOS japao = { "Japão", x, y, 1, 41 };
	DESTINOS paquistao = { "Paquistão", x, y, 1, 42 };
	DESTINOS russia = { "Rússia", x, y, 1, 43 };
	DESTINOS tailandia = { "Tailândia", x, y, 1, 44 };
	DESTINOS turquia = { "Turquia", x, y, 1, 45 };
	DESTINOS uzbequistão = { "Uzbequistão", x, y, 1, 46 };
	DESTINOS vietna = { "Vietnã", x, y, 1, 47 };
	DESTINOS alemanha = { "Alemanha", x, y, 1, 48 };
	DESTINOS austia = { "Áustria", x, y, 1, 49 };
	DESTINOS dinamarca = { "Dinamarca", x, y, 1, 50 };
	DESTINOS espanha = { "Espanha", x, y, 1, 51 };
	DESTINOS finlandia = { "Finlândia", x, y, 1, 52 };
	DESTINOS franca = { "França", x, y, 1, 53 };
	DESTINOS grecia = { "Grécia", x, y, 1, 54 };
	DESTINOS italia = { "Itália", x, y, 1, 55 };
	DESTINOS noruega = { "Noruega", x, y, 1, 56 };
	DESTINOS holanda = { "Holanda", x, y, 1, 57 };
	DESTINOS polonia = { "Polônia", x, y, 1, 58 };
	DESTINOS portugal = { "Portugal", x, y, 1, 59 };
	DESTINOS inglaterra = { "Inglaterra", x, y, 1, 60 };
	DESTINOS suecia = { "Suécia", x, y, 1, 61 };

	//Dificuldade 2
	DESTINOS bahamas;
		bahamas.nome = "Bahamas";
		bahamas.localizacao_x = x;
		bahamas.localizacao_y = y;
		bahamas.dificuldade = 2;
		bahamas.sorteio = 1;
	DESTINOS elSalvador;
		elSalvador.nome = "El Salvador";
		elSalvador.localizacao_x = x;
		elSalvador.localizacao_y = y;
		elSalvador.dificuldade = 2;
		elSalvador.sorteio = 2;
	DESTINOS guatemala;
		guatemala.nome = "Guatemala";
		guatemala.localizacao_x = x;
		guatemala.localizacao_y = y;
		guatemala.dificuldade = 2;
		guatemala.sorteio = 3;
	DESTINOS nicaragua;
		nicaragua.nome = "Nicarágua";
		nicaragua.localizacao_x = x;
		nicaragua.localizacao_y = y;
		nicaragua.dificuldade = 2;
		nicaragua.sorteio = 4;
	DESTINOS panama;
		panama.nome = "Panamá";
		panama.localizacao_x = x;
		panama.localizacao_y = y;
		panama.dificuldade = 2;
		panama.sorteio = 5;
	DESTINOS guiana;
		guiana.nome = "Guiana";
		guiana.localizacao_x = x;
		guiana.localizacao_y = y;
		guiana.dificuldade = 2;
		guiana.sorteio = 6;
	DESTINOS suriname;
		suriname.nome = "Suriname";
		suriname.localizacao_x = x;
		suriname.localizacao_y = y;
		suriname.dificuldade = 2;
		suriname.sorteio = 7;
	DESTINOS angola = { "Angola", x, y, 2, 8 };
	DESTINOS caboVerde = { "Cabo Verde", x, y, 2, 9 };
	DESTINOS etiopia = { "Etiópia", x, y, 2, 10 };
	DESTINOS guine = { "Guiné", x, y, 2, 11 };
	DESTINOS guineBissau = { "Guiné-Bissau", x, y, 2, 12 };
	DESTINOS guineEquatorial = { "Guiné Equatorial", x, y, 2, 13 };
	DESTINOS lesoto = { "Lesoto", x, y, 2, 14 };
	DESTINOS meuritania = { "Mauritânia", x, y, 2, 15 };
	DESTINOS niger = { "Níger", x, y, 2, 16 };
	DESTINOS quenia = { "Quênia", x, y, 2, 17 };
	DESTINOS republicaCongo = { "República do Congo", x, y, 2, 18 };
	DESTINOS republicaDemocraticaCongo = { "República Democrática do Congo", x, y, 2, 19 };
	DESTINOS saoTomePrincipe = { "São Tomé e Príncipe", x, y, 2, 20 };
	DESTINOS sudao = { "Sudão", x, y, 2, 21 };
	DESTINOS sudaoSul = { "Sudão do Sul", x, y, 2, 22 };
	DESTINOS tanzania = { "Tanzânia", x, y, 2, 23 };
	DESTINOS togo = { "Togo", x, y, 2, 24 };
	DESTINOS zambia = { "Zâmbia", x, y, 2, 25 };
	DESTINOS zimbabwe = { "Zimbabwe", x, y, 2, 26 };
	DESTINOS fiji = { "Fiji", x, y, 2, 27 };
	DESTINOS papuaNovaGuine = { "Papua-Nova Guiné", x, y, 2, 28 };
	DESTINOS afeganistao = { "Afeganistão", x, y, 2, 29 };
	DESTINOS azerbaijao = { "Azerbaijão", x, y, 2, 30 };
	DESTINOS camboja = { "Camboja", x, y, 2, 31 };
	DESTINOS filipinas = { "Filipinas", x, y, 2, 32 };
	DESTINOS georgia = { "Geórgia", x, y, 2, 33 };
	DESTINOS maldivas = { "Maldivas", x, y, 2, 34 };
	DESTINOS mongolia = { "Mongólia", x, y, 2, 35 };
	DESTINOS nepal = { "Nepal", x, y, 2, 36 };
	DESTINOS quirguistao = { "Quirguistão", x, y, 2, 37 };
	DESTINOS sriLanka = { "Sri Lanka", x, y, 2, 38 };
	DESTINOS albania = { "Albânia", x, y, 2, 39 };
	DESTINOS armenia = { "Armênia", x, y, 2, 40 };
	DESTINOS azerbaijao = { "Azerbaijão", x, y, 2, 41 };
	DESTINOS belgica = { "Bélgica", x, y, 2, 42 };
	DESTINOS bulgaria = { "Bulgária", x, y, 2, 43 };
	DESTINOS cazaquistao = { "Cazaquistão", x, y, 2, 44 };
	DESTINOS republicaTcheca = { "República Tcheca", x, y, 2, 45 };
	DESTINOS croacia = { "Croácia", x, y, 2, 46 };
	DESTINOS eslovaquia = { "Eslováquia", x, y, 2, 47 };
	DESTINOS eslovenia = { "Eslovênia", x, y, 2, 48 };
	DESTINOS hungria = { "Hungria", x, y, 2, 49 };
	DESTINOS irlanda = { "Irlanda", x, y, 2, 50 };
	DESTINOS islandia = { "Islândia", x, y, 2, 51 };
	DESTINOS luxemburgo = { "Luxemburgo", x, y, 2, 52 };
	DESTINOS monaco = { "Mônaco", x, y, 2, 53 };
	DESTINOS escocia = { "Escócia", x, y, 2, 54 };
	DESTINOS irlandaNorte = { "Irlanda do Norte", x, y, 2, 55 };
	DESTINOS servia = { "Sérvia", x, y, 2, 56 };
	DESTINOS suica = { "Suíça", x, y, 2, 57 };
	DESTINOS ucrania = { "Ucrânia", x, y, 2, 58 };
	DESTINOS guianaFrancesa = {"Guiana Francesa", x, y, 2, 59 };
	
	//Dificuldade 3
	DESTINOS belize;
		belize.nome = "Belize";
		belize.localizacao_x = x;
		belize.localizacao_y = y;	
		belize.dificuldade = 3;
		belize.sorteio = 1;
	DESTINOS argelia = { "Argélia", x, y, 3, 2 };
	DESTINOS benim = { "Benim", x, y, 3, 3 };
	DESTINOS botswana = { "Botswana", x, y, 3, 4 };
	DESTINOS burkinaFaso = { "Burkina Faso", x, y, 3, 5 };
	DESTINOS burundi = { "Burundi", x, y, 3, 6 };
	DESTINOS chade = { "Chade", x, y, 3, 7 };
	DESTINOS comores = { "Comores", x, y, 3, 8 };
	DESTINOS djibouti = { "Djibouti", x, y, 3, 9 };
	DESTINOS eritreia = { "Eritreia", x, y, 3, 10 };
	DESTINOS gabao = { "Gabão", x, y, 3, 11 };
	DESTINOS gambia = { "Gâmbia", x, y, 3, 12 };
	DESTINOS liberia = { "Libéria", x, y, 3, 13 };
	DESTINOS malawi = { "Malawi", x, y, 3, 14 };
	DESTINOS mali = { "Mali", x, y, 3, 15 };
	DESTINOS mauricia = { "Maurícia", x, y, 3, 16 };
	DESTINOS namibia = { "Namíbia", x, y, 3, 17 };
	DESTINOS republicaCentroAfricana = { "República Centro-Africana", x, y, 3, 18 };
	DESTINOS ruanda = { "Ruanda", x, y, 3, 19 };
	DESTINOS serraLeoa = { "Serra Leoa", x, y, 3, 20 };
	DESTINOS seychelles = { "Seychelles", x, y, 3, 21 };
	DESTINOS suazilandia = { "Suzilândia", x, y, 3, 22 };
	DESTINOS tunisia = { "Tunísia", x, y, 3, 23 };
	DESTINOS uganda = { "Uganda", x, y, 3, 24 };
	DESTINOS estadosFederadosMicronesia = { "Estados Federados ds Micronésia", x, y, 3, 25 };
	DESTINOS ilhasMarshall = { "Ilhas Marshall", x, y, 3, 26 };
	DESTINOS ilhasSalomao = { "Ilhas Salomão", x, y, 3, 27 };
	DESTINOS kiribati = { "Kiribati", x, y, 3, 28 };
	DESTINOS nauru = { "Nauru", x, y, 3, 29 };
	DESTINOS palau = { "Palau", x, y, 3, 30 };
	DESTINOS samoa = { "Samoa", x, y, 3, 31 };
	DESTINOS tonga = { "Tonga", x, y, 3, 32 };
	DESTINOS tuvalu = { "Tuavalu", x, y, 3, 33 };
	DESTINOS vanuatu = { "Vanuatu", x, y, 3, 34 };
	DESTINOS armenia = { "Armênia", x, y, 3, 35 };
	DESTINOS bahrein = { "Bahrein", x, y, 3, 36 };
	DESTINOS brunei = { "Brunei", x, y, 3, 37 };
	DESTINOS butao = { "Butão", x, y, 3, 38 };
	DESTINOS chipre = { "Chipre", x, y, 3, 39 };
	DESTINOS laos = { "Laos", x, y, 3, 40 };
	DESTINOS tajiquistao = { "Tajiquistão", x, y, 3, 41 };
	DESTINOS timorLester = { "Timor-Leste", x, y, 3, 42 };
	DESTINOS turquemenistao = { "Turquemenistao", x, y, 3, 43 };
	DESTINOS andorra = { "Andorra", x, y, 3, 44 };
	DESTINOS bielorrusia = { "Bielorrúsia", x, y, 3, 45 };
	DESTINOS bosniaHerzegovinia = { "Bósnia e Herzegovinia", x, y, 3, 46 };
	DESTINOS estonia = { "Estônia", x, y, 3, 47 };
	DESTINOS kosovo = { "Kosovo", x, y, 3, 48 };
	DESTINOS letonia = { "Letônia", x, y, 3, 49 };
	DESTINOS liechtenstein = { "Liechtenstein", x, y, 3, 50 };
	DESTINOS lituania = { "Lituânia", x, y, 3, 51 };
	DESTINOS malta = { "Malta", x, y, 3, 52 };
	DESTINOS moldavia = { "Moldávia", x, y, 3, 53 };
	DESTINOS montenegro = { "Montenegro", x, y, 3, 54 };
	DESTINOS paisGales = { "País de Gales", x, y, 3, 55 };
	DESTINOS macedonia = { "Macedônia", x, y, 3, 56 };
	DESTINOS romenia = { "Romênia", x, y, 3, 57 };
	DESTINOS sanMarino = { "San Marino", x, y, 3, 58 };*/
}
