typedef struct avioes {
	int x;
	int y;
	int velocidade;
	int combustivel;
	int placar;
} AVIOES;
typedef struct destinos {
	char *nome;
	int localizacao_x;
	int localizacao_y;
	int dificuldade;
	int sorteio;
} DESTINOS;

void iniciaDestinos(DESTINOS paises[]) {
	//Dificuldade 1
	DESTINOS canada;
		canada.nome = "Canadá";
		canada.localizacao_x = 513;	
		canada.localizacao_y = 341;
		canada.dificuldade = 1;
		canada.sorteio = 1;
	DESTINOS eua;
		eua.nome = "Estados Unidos da Améica";
		eua.localizacao_x = 474;
		eua.localizacao_y = 406;
		eua.dificuldade = 1;
		eua.sorteio = 2;
	DESTINOS mexico;
		mexico.nome = "México";
		mexico.localizacao_x = 336;
		mexico.localizacao_y = 519;
		mexico.dificuldade = 1;
		mexico.sorteio = 3;
	DESTINOS caribe;
		caribe.nome = "Caribe";
		caribe.localizacao_x = 439;
		caribe.localizacao_y = 505;
		caribe.dificuldade = 1;
		caribe.sorteio = 4;
	DESTINOS portoRico;
		portoRico.nome = "Porto Rico";
		portoRico.localizacao_x = 508;
		portoRico.localizacao_y = 533;
		portoRico.dificuldade = 1;
		portoRico.sorteio = 5;
	DESTINOS costaRica;
		costaRica.nome = "Costa Rica";
		costaRica.localizacao_x = 407;
		costaRica.localizacao_y = 585;
		costaRica.dificuldade = 1;
		costaRica.sorteio = 6;
	DESTINOS honduras;
		honduras.nome = "Honduras";
		honduras.localizacao_x = 395;
		honduras.localizacao_y = 554;
		honduras.dificuldade = 1;
		honduras.sorteio = 7;
	DESTINOS argentina;
		argentina.nome = "Argentina";
		argentina.localizacao_x = 566;
		argentina.localizacao_y = 854;
		argentina.dificuldade = 1;    
		argentina.sorteio = 8;
	DESTINOS bolivia;
		bolivia.nome = "Bolívia";
		bolivia.localizacao_x = 500;
		bolivia.localizacao_y = 741;
		bolivia.dificuldade = 1;
		bolivia.sorteio = 9;
	DESTINOS brasil;
		brasil.nome = "Brasil";
		brasil.localizacao_x = 609;
		brasil.localizacao_y = 750;
		brasil.dificuldade = 1;
		brasil.sorteio = 10;
	DESTINOS chile;
		chile.nome = "Chile";
		chile.localizacao_x = 497;
		chile.localizacao_y = 833;
		chile.dificuldade = 1;
		chile.sorteio = 11;
	DESTINOS colombia;
		colombia.nome = "Colômbia";
		colombia.localizacao_x = 463;
		colombia.localizacao_y = 610;
		colombia.dificuldade = 1;
		colombia.sorteio = 12;
	DESTINOS equador;
		equador.nome = "Equador";
		equador.localizacao_x = 437;
		equador.localizacao_y = 649;
		equador.dificuldade = 1;
		equador.sorteio = 13;
	DESTINOS paraguai;
		paraguai.nome = "Paraguai";
		paraguai.localizacao_x = 563;
		paraguai.localizacao_y = 786;
		paraguai.dificuldade = 1;
		paraguai.sorteio = 14;
	DESTINOS peru;
		peru.nome = "Peru";
		peru.localizacao_x = 451;
		peru.localizacao_y = 716;
		peru.dificuldade = 1;
		peru.dificuldade = 15;
	DESTINOS uruguai;
		uruguai.nome = "Uruguai";
		uruguai.localizacao_x = 576;
		uruguai.localizacao_y = 840;
		uruguai.dificuldade = 1;
		uruguai.sorteio = 16;
	DESTINOS venezuela;
		venezuela.nome = "Venezuela";
		venezuela.localizacao_x = 496;
		venezuela.localizacao_y = 580;
		venezuela.dificuldade = 1;
		venezuela.sorteio = 17;
	DESTINOS africaSul;
		africaSul.nome = "África do Sul";
		africaSul.localizacao_x = x;
		africaSul.localizacao_y = y;
		africaSul.dificuldade = 1;
		africaSul.sorteio = 18;
	DESTINOS camaroes;
		camaroes.nome = "Camarões";
		camaroes.localizacao_x = x;
		camaroes.localizacao_y = y;
		camaroes.dificuldade = 1;
		camaroes.sorteio = 19;
	DESTINOS costaMarfim;
		costaMarfim.nome = "Costa do Marfim";
		costaMarfim.localizacao_x = x;
		costaMarfim.localizacao_y = y;
		costaMarfim.dificuldade = 1;
		costaMarfim.sorteio = 20;
	DESTINOS egito;
		egito.nome = "Egito";
		egito.localizacao_x = x;
		egito.localizacao_y = y;
		egito.dificuldade = 1;
		egito.sorteio = 21;
	DESTINOS gana;
		gana.nome = "Gana";
		gana.localizacao_x = x;
		gana.localizacao_y = y;
		gana.dificuldade = 1;
		gana.sorteio = 22;
	DESTINOS libia;
		libia.nome = "Líbia";
		libia.localizacao_x = x;
		libia.localizacao_y = y;
		libia.dificuldade = 1;
		libia.sorteio = 23;
	DESTINOS madagascar;
		madagascar.nome = "Madagáscar";
		madagascar.localizacao_x = x;
		madagascar.localizacao_y = y;
		madagascar.dificuldade = 1;
		madagascar.sorteio = 24;
	DESTINOS marrocos;
		marrocos.nome = "Marrocos";
		marrocos.localizacao_x = x;
		marrocos.localizacao_y = y;
		marrocos.dificuldade = 1;
		marrocos.sorteio = 25;
	DESTINOS mocambique;
		mocambique.nome = "Moçambique";
		mocambique.localizacao_x = x;
		mocambique.localizacao_y = y;
		mocambique.dificuldade = 1;
		mocambique.sorteio = 26;
	DESTINOS nigeria;
		nigeria.nome = "Nigéria";
		nigeria.localizacao_x = x;
		nigeria.localizacao_y = y;
		nigeria.dificuldade = 1;
		nigeria.sorteio = 27;
	DESTINOS senegal;
		senegal.nome = "Senegal";
		senegal.localizacao_x = x;
		senegal.localizacao_y = y;
		senegal.dificuldade = 1;
		senegal.sorteio = 28;
	DESTINOS somalia;
		somalia.nome = "Somália";
		somalia.localizacao_x = x;
		somalia.localizacao_y = y;
		somalia.dificuldade = 1;
		somalia.sorteio = 29;
	DESTINOS australia;
		australia.nome = "Austrália";
		australia.localizacao_x = x;
		australia.localizacao_y = y;
		australia.dificuldade = 1;
		australia.sorteio = 30;
	DESTINOS novaZelandia;
		novaZelandia.nome = "Nova Zelândia";
		novaZelandia.localizacao_x = x;
		novaZelandia.localizacao_y = y;
		novaZelandia.dificuldade = 1;
		novaZelandia.sorteio = 31;
	DESTINOS arabiaSaudita;
		arabiaSaudita.nome = "Arábia Saudita";
		arabiaSaudita.localizacao_x = x;
		arabiaSaudita.localizacao_y = y;
		arabiaSaudita.dificuldade = 1;
		arabiaSaudita.sorteio = 32;
	DESTINOS bangladesh;
		bangladesh.nome = "Bangladesh";
		bangladesh.localizacao_x = x;
		bangladesh.localizacao_y = y;
		bangladesh.dificuldade = 1;
		bangladesh.sorteio = 33;
	DESTINOS cazaquistao;
		cazaquistao.nome = "Cazaquistão";
		cazaquistao.localizacao_x = x;
		cazaquistao.localizacao_y = y;
		cazaquistao.dificuldade = 1;
		cazaquistao.sorteio = 34;
	DESTINOS coreiaNorte;
		coreiaNorte.nome = "Coréia do Norte";
		coreiaNorte.localizacao_x = x;
		coreiaNorte.localizacao_y = y;
		coreiaNorte.dificuldade = 1;
		coreiaNorte.sorteio = 35;
	DESTINOS coreiaSul;
		coreiaSul.nome = "Coréia do Sul";
		coreiaSul.localizacao_x = x;
		coreiaSul.localizacao_y = y;
		coreiaSul.dificuldade = 1;
		coreiaSul.sorteio = 36;
	DESTINOS indonesia;
		indonesia.nome = "Indonésia";
		indonesia.localizacao_x = x;
		indonesia.localizacao_y = y;
		indonesia.dificuldade = 1;
		indonesia.sorteio = 37;
	DESTINOS india;
		india.nome = "Índia";
		india.localizacao_x = x;
		india.localizacao_y = y;
		india.dificuldade = 1;
		india.sorteio = 38;
	DESTINOS ira;
		ira.nome = "Irã";
		ira.localizacao_x = x;
		ira.localizacao_y = y;
		ira.dificuldade = 1;
		ira.sorteio = 39;
	DESTINOS iraque;
		iraque.nome = "Iraque";
		iraque.localizacao_x = x;
		iraque.localizacao_y = y;
		iraque.dificuldade = 1;
		iraque.sorteio = 40;
	DESTINOS japao;
		japao.nome = "Japão";
		japao.localizacao_x = x;
		japao.localizacao_y = y;
		japao.dificuldade = 1;
		japao.sorteio = 41;
	DESTINOS paquistao;
		paquistao.nome = "Paquistão";
		paquistao.localizacao_x = x;
		paquistao.localizacao_y = y;
		paquistao.dificuldade = 1;
		paquistao.sorteio = 42;
	DESTINOS russia;
		russia.nome = "Rússia";
		russia.localizacao_x = x;
		russia.localizacao_y = y;
		russia.dificuldade = 1;
		russia.sorteio = 43;
	DESTINOS tailandia;
		tailandia.nome = "Tailândia";
		tailandia.localizacao_x = x;
		tailandia.localizacao_y = y;
		tailandia.dificuldade = 1;
		tailandia.sorteio = 44;
	DESTINOS turquia;
		turquia.nome = "Turquia";
		turquia.localizacao_x = x;
		turquia.localizacao_y = y;
		turquia.dificuldade = 1;
		turquia.sorteio = 45;
	DESTINOS uzbequistao;
		uzbequistao.nome = "Uzbequistão";
		uzbequistao.localizacao_x = x;
		uzbequistao.localizacao_y = y;
		uzbequistao.dificuldade = 1;
		uzbequistao.sorteio = 46;
	DESTINOS vietna;
		vietna.nome = "Vietnã";
		vietna.localizacao_x = x;
		vietna.localizacao_y = y;
		vietna.dificuldade = 1;
		vietna.sorteio = 47;
	DESTINOS alemanha;
		alemanha.nome = "Alemanha";
		alemanha.localizacao_x = x;
		alemanha.localizacao_y = y;
		alemanha.dificuldade = 1;
		alemanha.sorteio = 48;
	DESTINOS austia;
		australia.nome = "Áustria";
		australia.localizacao_x = x;
		australia.localizacao_y = y;
		australia.dificuldade = 1;
		australia.sorteio = 49;
	DESTINOS dinamarca;
		dinamarca.nome = "Dinamarca";
		dinamarca.localizacao_x = x;
		dinamarca.localizacao_y = y;
		dinamarca.dificuldade = 1;
		dinamarca.sorteio = 50;
	DESTINOS espanha;
		espanha.nome = "Espanha";
		espanha.localizacao_x = x;
		espanha.localizacao_y = y;
		espanha.dificuldade = 1;
		espanha.sorteio = 51;
	DESTINOS finlandia;
		finlandia.nome = "Finlândia";
		finlandia.localizacao_x = x;
		finlandia.localizacao_y = y;
		finlandia.dificuldade = 1;
		finlandia.sorteio = 52;
	DESTINOS franca;
		franca.nome = "França";
		franca.localizacao_x = x;
		franca.localizacao_y = y;
		franca.dificuldade = 1;
		franca.sorteio = 53;
	DESTINOS grecia;
		grecia.nome = "Grécia";
		grecia.localizacao_x = x;
		grecia.localizacao_y = y;
		grecia.dificuldade = 1;
		grecia.sorteio = 54;
	DESTINOS italia;
		italia.nome = "Itália";
		italia.localizacao_x = x;
		italia.localizacao_y = y;
		italia.dificuldade = 1;
		italia.sorteio = 55;
	DESTINOS noruega;
		noruega.nome = "Noruega";
		noruega.localizacao_x = x;
		noruega.localizacao_y = y;
		noruega.dificuldade = 1;
		noruega.sorteio = 56;
	DESTINOS holanda;
		holanda.nome = "Holanda";
		holanda.localizacao_x = x;
		holanda.localizacao_x = y;
		holanda.dificuldade = 1;
		holanda.sorteio = 57;
	DESTINOS polonia;
		polonia.nome = "Polônia";
		polonia.localizacao_x = x;
		polonia.localizacao_y = y;
		polonia.dificuldade = 1;
		polonia.sorteio = 58;
	DESTINOS portugal;
		portugal.nome = "Portugal";
		portugal.localizacao_x = x;
		portugal.localizacao_y = y;
		portugal.dificuldade = 1;
		portugal.sorteio = 59;
	DESTINOS inglaterra;
		inglaterra.nome = "Inglaterra";
		inglaterra.localizacao_x = x;
		inglaterra.localizacao_y = y;
		inglaterra.dificuldade = 1;
		inglaterra.sorteio = 60;
	DESTINOS suecia;
		suecia.nome = "Suécia";
		suecia.localizacao_x = x;
		suecia.localizacao_y = y;
		suecia.dificuldade = 1;
		suecia.sorteio = 61;

	//Dificuldade 2
	DESTINOS bahamas;
		bahamas.nome = "Bahamas";
		bahamas.localizacao_x = 452;
		bahamas.localizacao_y = 495;
		bahamas.dificuldade = 2;
		bahamas.sorteio = 1;
	DESTINOS elSalvador;
		elSalvador.nome = "El Salvador";
		elSalvador.localizacao_x = 387;
		elSalvador.localizacao_y = 558;
		elSalvador.dificuldade = 2;
		elSalvador.sorteio = 2;
	DESTINOS guatemala;
		guatemala.nome = "Guatemala";
		guatemala.localizacao_x = 380;
		guatemala.localizacao_y = 549;
		guatemala.dificuldade = 2;
		guatemala.sorteio = 3;
	DESTINOS nicaragua;
		nicaragua.nome = "Nicarágua";
		nicaragua.localizacao_x = 400;
		nicaragua.localizacao_y = 567;
		nicaragua.dificuldade = 2;
		nicaragua.sorteio = 4;
	DESTINOS panama;
		panama.nome = "Panamá";
		panama.localizacao_x = 419;
		panama.localizacao_y = 591;
		panama.dificuldade = 2;
		panama.sorteio = 5;
	DESTINOS guiana;
		guiana.nome = "Guiana";
		guiana.localizacao_x = 544;
		guiana.localizacao_y = 605;
		guiana.dificuldade = 2;
		guiana.sorteio = 6;
	DESTINOS suriname;
		suriname.nome = "Suriname";
		suriname.localizacao_x = 561;
		suriname.localizacao_y = 612;
		suriname.dificuldade = 2;
		suriname.sorteio = 7;
	DESTINOS angola;
		angola.nome = "Angola";
		angola.localizacao_x = x;
		angola.localizacao_y = y;
		angola.dificuldade = 2;
		angola.sorteio = 8;
	DESTINOS caboVerde;
		caboVerde.nome = "Cabo Verde";
		caboVerde.localizacao_x = x;
		caboVerde.localizacao_y = y;
		caboVerde.dificuldade = 2;
		caboVerde.sorteio = 9;
	DESTINOS etiopia;
		etiopia.nome = "Etiópia";
		etiopia.localizacao_x = x; 
		etiopia.localizacao_y = y;
		etiopia.dificuldade = 2;
		etiopia.sorteio = 10;
	DESTINOS guine;
		guine.nome = "Guiné";
		guine.localizacao_x = x;
		guine.localizacao_y = y;
		guine.dificuldade = 2;
		guine.sorteio = 11;
	DESTINOS guineBissau;
		guineBissau.nome = "Guiné-Bissau";
		guineBissau.localizacao_x = x;
		guineBissau.localizacao_y = y;
		guineBissau.dificuldade = 2;
		guineBissau.sorteio = 12;
	DESTINOS guineEquatorial;
		guineEquatorial.nome = "Guiné Equatorial";
		guineEquatorial.localizacao_x = x;
		guineEquatorial.localizacao_y = y;
		guineEquatorial.dificuldade = 2;
		guineEquatorial.sorteio = 13;
	DESTINOS lesoto;
		lesoto.nome = "Lesoto";
		lesoto.localizacao_x = x;
		lesoto.localizacao_y = y;
		lesoto.dificuldade = 2;
		lesoto.sorteio = 14;
	DESTINOS mauritania;
		mauritania.nome = "Mauritânia";
		mauritania.localizacao_x = x;
		mauritania.localizacao_y = y;
		mauritania.dificuldade = 2;
		mauritania.sorteio = 15;
	DESTINOS niger;
		niger.nome = "Níger";
		niger.localizacao_x = x;
		niger.localizacao_y = y;
		niger.dificuldade = 2;
		niger.sorteio = 16;
	DESTINOS quenia;
		quenia.nome = "Quênia";
		quenia.localizacao_x = x;
		quenia.localizacao_y = y;
		quenia.dificuldade = 2;
		quenia.sorteio = 17;
	DESTINOS republicaCongo;
		republicaCongo.nome = "República do Congo";
		republicaCongo.localizacao_x = x;
		republicaCongo.localizacao_y = y;
		republicaCongo.dificuldade = 2;
		republicaCongo.sorteio = 18;
	DESTINOS saoTomePrincipe;
		saoTomePrincipe.nome = "São Tomé e Príncipe";
		saoTomePrincipe.localizacao_x = x;
		saoTomePrincipe.localizacao_y = y;
		saoTomePrincipe.dificuldade = 2;
		saoTomePrincipe.sorteio = 20;
	DESTINOS sudao;
		sudao.nome = "Sudão";
		sudao.localizacao_x = x;
		sudao.localizacao_y = y;
		sudao.dificuldade = 2;
		sudao.sorteio = 21;
	DESTINOS sudaoSul;
		sudaoSul.nome = "Sudão do Sul";
		sudaoSul.localizacao_x = x;
		sudaoSul.localizacao_y = y;
		sudaoSul.dificuldade = 2;
		sudaoSul.sorteio = 22;
	DESTINOS tanzania;
		tanzania.nome = "Tanzânia";
		tanzania.localizacao_x = x;
		tanzania.localizacao_y = y;
		tanzania.dificuldade = 2;
		tanzania.sorteio = 23;
	DESTINOS togo;
		togo.nome = "Togo";
		togo.localizacao_x = x;
		togo.localizacao_y = y;
		togo.dificuldade = 2;
		togo.sorteio = 24;
	DESTINOS zambia;
		zambia.nome = "Zâmbia";
		zambia.localizacao_x = x;
		zambia.localizacao_y = y;
		zambia.dificuldade = 2;
		zambia.sorteio = 25;
	DESTINOS zimbabwe;
		zimbabwe.nome = "Zimbabwe";
		zimbabwe.localizacao_x = x;
		zimbabwe.localizacao_y = y;
		zimbabwe.dificuldade = 2;
		zimbabwe.sorteio = 26;
	DESTINOS fiji;
		fiji.nome = "Fiji";
		fiji.localizacao_x = x;
		fiji.localizacao_y = y;
		fiji.dificuldade = 2;
		fiji.sorteio = 27;
	DESTINOS papuaNovaGuine;
		papuaNovaGuine.nome = "Papua-Nova Guiné";
		papuaNovaGuine.localizacao_x = x;
		papuaNovaGuine.localizacao_y = y;
		papuaNovaGuine.dificuldade = 2;
		papuaNovaGuine.sorteio = 28;
	DESTINOS afeganistao;
		afeganistao.nome = "Afeganistão";
		afeganistao.localizacao_x = x;
		afeganistao.localizacao_y = y;
		afeganistao.dificuldade = 2;
		afeganistao.sorteio = 29;
	DESTINOS azerbaijao;
		azerbaijao.nome = "Azerbaijão";
		azerbaijao.localizacao_x = x;
		azerbaijao.localizacao_y = y;
		azerbaijao.dificuldade = 2;
		azerbaijao.sorteio = 30;
	DESTINOS camboja;
		camboja.nome = "Camboja";
		camboja.localizacao_x = x;
		camboja.localizacao_y = y;
		camboja.dificuldade = 2;
		camboja.sorteio = 31;
	DESTINOS filipinas;
		filipinas.nome = "Filipinas";
		filipinas.localizacao_x = x;
		filipinas.localizacao_y = y;
		filipinas.dificuldade = 2;
		filipinas.sorteio = 32;
	DESTINOS georgia;
		georgia.nome = "Geórgia";
		georgia.localizacao_x = x;
		georgia.localizacao_y = y;
		georgia.dificuldade = 2;
		georgia.sorteio = 33;
	DESTINOS maldivas;
		maldivas.nome = "Maldivas";
		maldivas.localizacao_x = x;
		maldivas.localizacao_y = y;
		maldivas.dificuldade = 2;
		maldivas.sorteio = 34;
	DESTINOS mongolia;
		mongolia.nome = "Mongólia";
		mongolia.localizacao_x = x;
		mongolia.localizacao_y = y;
		mongolia.dificuldade = 2;
		mongolia.sorteio = 35;
	DESTINOS nepal;
		nepal.nome = "Nepal";
		nepal.localizacao_x = x;
		nepal.localizacao_y = y;
		nepal.dificuldade = 2;
		nepal.sorteio = 36;
	DESTINOS quirguistao;
		quirguistao.nome = "Quirguistão";
		quirguistao.localizacao_x = x;
		quirguistao.localizacao_y = y;
		quirguistao.dificuldade = 2;
		quirguistao.sorteio = 37;
	DESTINOS sriLanka;
		sriLanka.nome = "Sri Lanka";
		sriLanka.localizacao_x = x;
		sriLanka.localizacao_y = y;
		sriLanka.dificuldade = 2;
		sriLanka.sorteio = 38;
	DESTINOS albania;
		albania.nome = "Albânia";
		albania.localizacao_x = x;
		albania.localizacao_y = y;
		albania.dificuldade = 2;
		albania.sorteio = 39;
	DESTINOS armenia;
		armenia.nome = "Armênia";
		armenia.localizacao_x = x;
		armenia.localizacao_y = y;
		armenia.dificuldade = 2;
		armenia.sorteio = 40;
	DESTINOS azerbaijao;
		azerbaijao.nome = "Azerbaijão";
		azerbaijao.localizacao_x = x;
		azerbaijao.localizacao_y = y;
		azerbaijao.dificuldade = 2;
		azerbaijao.sorteio = 41;
	DESTINOS belgica;
		belgica.nome = "Bélgica";
		belgica.localizacao_x = x;
		belgica.localizacao_y = y;
		belgica.dificuldade = 2;
		belgica.sorteio = 42;
	DESTINOS bulgaria;
		bulgaria.nome = "Bulgária";
		bulgaria.localizacao_x = x;
		bulgaria.localizacao_y = y;
		bulgaria.dificuldade = 2;
		bulgaria.sorteio = 43;
	DESTINOS cazaquistao;
		cazaquistao.nome = "Cazaquistão";
		cazaquistao.localizacao_x = x;
		cazaquistao.localizacao_y = y;
		cazaquistao.dificuldade = 2;
		cazaquistao.sorteio = 44;
	DESTINOS republicaTcheca;
		republicaTcheca.nome = "República Tcheca";
		republicaTcheca.localizacao_x = x;
		republicaTcheca.localizacao_y = y;
		republicaTcheca.dificuldade = 2;
		republicaTcheca.sorteio = 45;
	DESTINOS croacia;
		croacia.nome = "Croácia";
		croacia.localizacao_x = x;
		croacia.localizacao_y = y;
		croacia.dificuldade = 2;
		croacia.sorteio = 46;
	DESTINOS eslovaquia;
		eslovaquia.nome = "Eslováquia";
		eslovaquia.localizacao_x = x;
		eslovaquia.localizacao_y = y;
		eslovaquia.dificuldade = 2;
		eslovaquia.sorteio = 47;
	DESTINOS eslovenia;
		eslovenia.nome = "Eslovênia";
		eslovenia.localizacao_x = x;
		eslovenia.localizacao_y = y;
		eslovenia.dificuldade = 2;
		eslovenia.sorteio = 48;
	DESTINOS hungria;
		hungria.nome = "Hungria";
		hungria.localizacao_x = x;
		hungria.localizacao_y = y;
		hungria.dificuldade = 2;
		hungria.sorteio = 49;
	DESTINOS irlanda;
		irlanda.nome = "Irlanda";
		irlanda.localizacao_x = x;
		irlanda.localizacao_y = y;
		irlanda.dificuldade = 2;
		irlanda.sorteio = 50;
	DESTINOS islandia;
		islandia.nome = "Islândia";
		islandia.localizacao_x = x;
		islandia.localizacao_y = y;
		islandia.dificuldade = 2;
		islandia.sorteio = 51;
	DESTINOS luxemburgo;
		luxemburgo.nome = "Luxemburgo";
		luxemburgo.localizacao_x = x;
		luxemburgo.localizacao_y = y;
		luxemburgo.dificuldade = 2;
		luxemburgo.sorteio = 52;
	DESTINOS monaco;
		monaco.nome = "Mônaco";
		monaco.localizacao_x = x;
		monaco.localizacao_y = y;
		monaco.dificuldade = 2;
		monaco.sorteio = 53;
	DESTINOS escocia;
		escocia.nome = "Escócia";
		escocia.localizacao_x = x;
		escocia.localizacao_y = y;
		escocia.dificuldade = 2;
		escocia.sorteio = 54;
	DESTINOS irlandaNorte;
		irlandaNorte.nome = "Irlanda do Norte";
		irlandaNorte.localizacao_x = x;
		irlandaNorte.localizacao_y = y;
		irlandaNorte.dificuldade = 2;
		irlandaNorte.sorteio = 55;
	DESTINOS servia;
		servia.nome = "Sérvia";
		servia.localizacao_x = x;
		servia.localizacao_y = y;
		servia.dificuldade = 2;
		servia.sorteio = 56;
	DESTINOS suica;
		suica.nome = "Suíça";
		suica.localizacao_x = x;
		suica.localizacao_y = y;
		suica.dificuldade = 2;
		suica.sorteio = 57;
	DESTINOS ucrania;
		ucrania.nome = "Ucrânia";
		ucrania.localizacao_x = x;
		ucrania.localizacao_y = y;
		ucrania.dificuldade = 2;
		ucrania.sorteio = 58;
	DESTINOS guianaFrancesa;
		guianaFrancesa.nome = "Guiana Francesa";
		guianaFrancesa.localizacao_x = 579;
		guianaFrancesa.localizacao_y = 615;
		guianaFrancesa.dificuldade = 2;
		guianaFrancesa.sorteio = 59;
	
	//Dificuldade 3
	DESTINOS belize;
		belize.nome = "Belize";
		belize.localizacao_x = 390;
		belize.localizacao_y = 537;	
		belize.dificuldade = 3;
		belize.sorteio = 1;
	DESTINOS argelia;
		argelia.nome = "Argélia";
		argelia.localizacao_x = x;
		argelia.localizacao_y = y;
		argelia.dificuldade = 3;
		argelia.sorteio = 2;
	DESTINOS benim;
		benim.nome = "Benim";
		benim.localizacao_x = x;
		benim.localizacao_y = y;
		benim.dificuldade = 3;
		benim.sorteio = 3;
	DESTINOS botswana;
		botswana.nome = "Botswana";
		botswana.localizacao_x = x;
		botswana.localizacao_y = y;
		botswana.dificuldade = 3;
		botswana.sorteio = 4;
	DESTINOS burkinaFaso;
		burkinaFaso.nome = "Burkina Faso";
		burkinaFaso.localizacao_x = x;
		burkinaFaso.localizacao_y = y;
		burkinaFaso.dificuldade = 3;
		burkinaFaso.sorteio = 5;
	DESTINOS burundi;
		burundi.nome = "Burundi";
		burundi.localizacao_x = x;
		burundi.localizacao_y = y;
		burundi.dificuldade = 3;
		burundi.sorteio = 6;
	DESTINOS chade;
		chade.nome = "Chade";
		chade.localizacao_x = x;
		chade.localizacao_y = y;
		chade.dificuldade = 3;
		chade.sorteio = 7;
	DESTINOS comores;
		comores.nome = "Comores";
		comores.localizacao_x = x;
		comores.localizacao_y = y;
		comores.dificuldade = 3;
		comores.sorteio = 8;
	DESTINOS djibouti;
		djibouti.nome = "Djibouti";
		djibouti.localizacao_x = x;
		djibouti.localizacao_y = y;
		djibouti.dificuldade = 3;
		djibouti.sorteio = 9;
	DESTINOS eritreia;
		eritreia.nome = "Eritreia";
		eritreia.localizacao_x = x;
		eritreia.localizacao_y = y;
		eritreia.dificuldade = 3;
		eritreia.sorteio = 10;
	DESTINOS gabao;
		gabao.nome = "Gabão";
		gabao.localizacao_x = x;
		gabao.localizacao_y = y;
		gabao.dificuldade = 3;
		gabao.sorteio = 11;
	DESTINOS gambia;
		gambia.nome = "Gâmbia";
		gambia.localizacao_x = x;
		gambia.localizacao_y = y;
		gambia.dificuldade = 3;
		gambia.sorteio = 12;
	DESTINOS liberia;
		liberia.nome = "Libéria";
		liberia.localizacao_x = x;
		liberia.localizacao_y = y;
		libeira.dificuldade = 3;
		liberia.sorteio = 13;
	DESTINOS malawi;
		malawi.nome = "Malawi";
		malawi.localizacao_x = x;
		malawi.localizacao_y = y;
		malawi.dificuldade = 3;
		malawi.sorteio = 14;
	DESTINOS mali;
		mali.nome = "Mali";
		mali.localizacao_x = x;
		mali.localizacao_y = y;
		mali.dificuldade = 3;
		mali.sorteio = 15;
	DESTINOS mauricia;
		mauricia.nome = "Maurícia";
		mauricia.localizacao_x = x;
		mauricia.localizacao_y = y;
		mauricia.dificuldade = 3;
		mauricia.sorteio = 16;
	DESTINOS namibia;
		namibia.nome = "Namíbia";
		namibia.localizacao_x = x;
		namibia.localizacao_y = y;
		namibia.dificuldade = 3;
		namibia.sorteio = 17;
	DESTINOS republicaCentroAfricana;
		republicaCentroAfricana.nome = "República Centro-Africana";
		republicaCentroAfricana.localizacao_x = x;
		republicaCentroAfricana.localizacao_y = y;
		republicaCentroAfricana.dificuldade = 3;
		republicaCentroAfricana.sorteio = 18;
	DESTINOS ruanda;
		ruanda.nome = "Ruanda";
		ruanda.localizacao_x = x;
		ruanda.localizacao_y = y;
		ruanda.dificuldade = 3;
		ruanda.sorteio = 19;
	DESTINOS serraLeoa;
		serraLeoa.nome = "Serra Leoa";
		serraLeoa.localizacao_x = x;
		serraLeoa.localizacao_y = y;
		serraLeoa.dificuldade = 3;
		serraLeoa.sorteio = 20;
	DESTINOS seychelles;
		seychelles.nome = "Seychelles";
		seychelles.localizacao_x = x;
		seychelles.localizacao_y = y;
		seychelles.dificuldade = 3;
		seychelles.sorteio = 21;
	DESTINOS suzilandia;
		suzilandia.nome = "Suzilândia";
		suzilandia.localizacao_x = x;
		suzilandia.localizacao_y = y;
		suzilandia.dificuldade = 3;
		suzilandia.sorteio = 22;
	DESTINOS tunisia;
		tunisia.nome = "Tunísia";
		tunisia.localizacao_x = x;
		tunisia.localizacao_y = y;
		tunisia.dificuldade = 3;
		tunisia.sorteio = 23;
	DESTINOS uganda;
		uganda.nome = "Uganda";
		uganda.localizacao_x = x;
		ugande.localizacao_y = y;
		uganda.dificuldade = 3;
		uganda.sorteio = 24;
	DESTINOS estadosFederadosMicronesia;
		estadosFederadosMicronesia.nome = "Estados Federados ds Micronésia";
		estadosFederadosMicronesia.localizacao_x = x;
		estadosFederadosMicronesia.localizacao_y = y;
		estadosFederadosMicronesia.dificuldade = 3;
		estadosFederadosMicroneisa.sorteio = 25;
	DESTINOS ilhasMarshall;
		ilhasMarshall.nome = "Ilhas Marshall";
		ilhasMarshall.localizacao_x = x;
		ilhasMarshall.localizacao_y = y;
		ilhasMarshall.dificuldade = 3;
		ilhasMarshall.sorteio = 26;
	/*DESTINOS ilhasSalomao;
	= { "Ilhas Salomão", x, y, 3, 27 };
	DESTINOS kiribati;
	= { "Kiribati", x, y, 3, 28 };
	DESTINOS nauru;
	= { "Nauru", x, y, 3, 29 };
	DESTINOS palau;
	= { "Palau", x, y, 3, 30 };
	DESTINOS samoa;
	= { "Samoa", x, y, 3, 31 };
	DESTINOS tonga;
	= { "Tonga", x, y, 3, 32 };
	DESTINOS tuvalu;
	= { "Tuavalu", x, y, 3, 33 };
	DESTINOS vanuatu;
	= { "Vanuatu", x, y, 3, 34 };
	DESTINOS armenia;
	= { "Armênia", x, y, 3, 35 };
	DESTINOS bahrein;
	= { "Bahrein", x, y, 3, 36 };
	DESTINOS brunei;
	= { "Brunei", x, y, 3, 37 };
	DESTINOS butao;
	= { "Butão", x, y, 3, 38 };
	DESTINOS chipre;
	= { "Chipre", x, y, 3, 39 };
	DESTINOS laos;
	= { "Laos", x, y, 3, 40 };
	DESTINOS tajiquistao;
	= { "Tajiquistão", x, y, 3, 41 };
	DESTINOS timorLester;
	= { "Timor-Leste", x, y, 3, 42 };
	DESTINOS turquemenistao;
	= { "Turquemenistao", x, y, 3, 43 };
	DESTINOS andorra;
	= { "Andorra", x, y, 3, 44 };
	DESTINOS bielorrusia;
	= { "Bielorrúsia", x, y, 3, 45 };
	DESTINOS bosniaHerzegovinia;
	= { "Bósnia e Herzegovinia", x, y, 3, 46 };
	DESTINOS estonia;
	= { "Estônia", x, y, 3, 47 };
	DESTINOS kosovo;
	= { "Kosovo", x, y, 3, 48 };
	DESTINOS letonia;
	= { "Letônia", x, y, 3, 49 };
	DESTINOS liechtenstein;
	= { "Liechtenstein", x, y, 3, 50 };
	DESTINOS lituania;
	= { "Lituânia", x, y, 3, 51 };
	DESTINOS malta;
	= { "Malta", x, y, 3, 52 };
	DESTINOS moldavia;
	= { "Moldávia", x, y, 3, 53 };
	DESTINOS montenegro;
	= { "Montenegro", x, y, 3, 54 };
	DESTINOS paisGales;
	= { "País de Gales", x, y, 3, 55 };
	DESTINOS macedonia;
	= { "Macedônia", x, y, 3, 56 };
	DESTINOS romenia;
	= { "Romênia", x, y, 3, 57 };
	DESTINOS sanMarino;
	= { "San Marino", x, y, 3, 58 };*/
}
