typedef struct avioes {
	int x;
	int y;
	int velocidade;
	int combustivel;
	int placar;
} AVIOES;
typedef struct destinos {
	char *nome;
	int localizacao_x;
	int localizacao_y;
	int dificuldade;
	int sorteio;
} DESTINOS;

void iniciaDestinos(DESTINOS paises[]) {
	//Dificuldade 1
	DESTINOS canada;
		canada.nome = "Canadá";
		canada.localizacao_x = 513;	
		canada.localizacao_y = 341;
		canada.dificuldade = 1;
		canada.sorteio = 1;
	DESTINOS eua;
		eua.nome = "Estados Unidos da Améica";
		eua.localizacao_x = 474;
		eua.localizacao_y = 406;
		eua.dificuldade = 1;
		eua.sorteio = 2;
	DESTINOS mexico;
		mexico.nome = "México";
		mexico.localizacao_x = 336;
		mexico.localizacao_y = 519;
		mexico.dificuldade = 1;
		mexico.sorteio = 3;
	DESTINOS caribe;
		caribe.nome = "Caribe";
		caribe.localizacao_x = 439;
		caribe.localizacao_y = 505;
		caribe.dificuldade = 1;
		caribe.sorteio = 4;
	DESTINOS portoRico;
		portoRico.nome = "Porto Rico";
		portoRico.localizacao_x = 508;
		portoRico.localizacao_y = 533;
		portoRico.dificuldade = 1;
		portoRico.sorteio = 5;
	DESTINOS costaRica;
		costaRica.nome = "Costa Rica";
		costaRica.localizacao_x = 407;
		costaRica.localizacao_y = 585;
		costaRica.dificuldade = 1;
		costaRica.sorteio = 6;
	DESTINOS honduras;
		honduras.nome = "Honduras";
		honduras.localizacao_x = 395;
		honduras.localizacao_y = 554;
		honduras.dificuldade = 1;
		honduras.sorteio = 7;
	DESTINOS argentina;
		argentina.nome = "Argentina";
		argentina.localizacao_x = 566;
		argentina.localizacao_y = 854;
		argentina.dificuldade = 1;    
		argentina.sorteio = 8;
	DESTINOS bolivia;
		bolivia.nome = "Bolívia";
		bolivia.localizacao_x = 500;
		bolivia.localizacao_y = 741;
		bolivia.dificuldade = 1;
		bolivia.sorteio = 9;
	DESTINOS brasil;
		brasil.nome = "Brasil";
		brasil.localizacao_x = 609;
		brasil.localizacao_y = 750;
		brasil.dificuldade = 1;
		brasil.sorteio = 10;
	DESTINOS chile;
		chile.nome = "Chile";
		chile.localizacao_x = 497;
		chile.localizacao_y = 833;
		chile.dificuldade = 1;
		chile.sorteio = 11;
	DESTINOS colombia;
		colombia.nome = "Colômbia";
		colombia.localizacao_x = 463;
		colombia.localizacao_y = 610;
		colombia.dificuldade = 1;
		colombia.sorteio = 12;
	DESTINOS equador;
		equador.nome = "Equador";
		equador.localizacao_x = 437;
		equador.localizacao_y = 649;
		equador.dificuldade = 1;
		equador.sorteio = 13;
	DESTINOS paraguai;
		paraguai.nome = "Paraguai";
		paraguai.localizacao_x = 563;
		paraguai.localizacao_y = 786;
		paraguai.dificuldade = 1;
		paraguai.sorteio = 14;
	DESTINOS peru;
		peru.nome = "Peru";
		peru.localizacao_x = 451;
		peru.localizacao_y = 716;
		peru.dificuldade = 1;
		peru.dificuldade = 15;
	DESTINOS uruguai;
		uruguai.nome = "Uruguai";
		uruguai.localizacao_x = 576;
		uruguai.localizacao_y = 840;
		uruguai.dificuldade = 1;
		uruguai.sorteio = 16;
	DESTINOS venezuela;
		venezuela.nome = "Venezuela";
		venezuela.localizacao_x = 496;
		venezuela.localizacao_y = 580;
		venezuela.dificuldade = 1;
		venezuela.sorteio = 17;
	DESTINOS africaSul;
		africaSul.nome = "África do Sul";
		africaSul.localizacao_x = 1003;
		africaSul.localizacao_y = 786;
		africaSul.dificuldade = 1;
		africaSul.sorteio = 18;
	DESTINOS camaroes;
		camaroes.nome = "Camarões";
		camaroes.localizacao_x = 920;
		camaroes.localizacao_y = 620;
		camaroes.dificuldade = 1;
		camaroes.sorteio = 19;
	DESTINOS costaMarfim;
		costaMarfim.nome = "Costa do Marfim";
		costaMarfim.localizacao_x = 830;
		costaMarfim.localizacao_y = 605;
		costaMarfim.dificuldade = 1;
		costaMarfim.sorteio = 20;
	DESTINOS egito;
		egito.nome = "Egito";
		egito.localizacao_x = 1034;
		egito.localizacao_y = 546;
		egito.dificuldade = 1;
		egito.sorteio = 21;
	DESTINOS gana;
		gana.nome = "Gana";
		gana.localizacao_x = 856;
		gana.localizacao_y = 609;
		gana.dificuldade = 1;
		gana.sorteio = 22;
	DESTINOS libia;
		libia.nome = "Líbia";
		libia.localizacao_x = 925;
		libia.localizacao_y = 454;
		libia.dificuldade = 1;
		libia.sorteio = 23;
	DESTINOS madagascar;
		madagascar.nome = "Madagascar";
		madagascar.localizacao_x = 1110;
		madagascar.localizacao_y = 742;
		madagascar.dificuldade = 1;
		madagascar.sorteio = 24;
	DESTINOS marrocos;
		marrocos.nome = "Marrocos";
		marrocos.localizacao_x = 825;
		marrocos.localizacao_y = 450;
		marrocos.dificuldade = 1;
		marrocos.sorteio = 25;
	DESTINOS mocambique;
		mocambique.nome = "Moçambique";
		mocambique.localizacao_x = 1035;
		mocambique.localizacao_y = 782;
		mocambique.dificuldade = 1;
		mocambique.sorteio = 26;
	DESTINOS nigeria;
		nigeria.nome = "Nigéria";
		nigeria.localizacao_x = 895;
		nigeria.localizacao_y = 591;
		nigeria.dificuldade = 1;
		nigeria.sorteio = 27;
	DESTINOS senegal;
		senegal.nome = "Senegal";
		senegal.localizacao_x = 768;
		senegal.localizacao_y = 558;
		senegal.dificuldade = 1;
		senegal.sorteio = 28;
	DESTINOS somalia;
		somalia.nome = "Somália";
		somalia.localizacao_x = 1095;
		somalia.localizacao_y = 635;
		somalia.dificuldade = 1;
		somalia.sorteio = 29;
	DESTINOS australia;
		australia.nome = "Austrália";
		australia.localizacao_x = 1606;
		australia.localizacao_y = 899;
		australia.dificuldade = 1;
		australia.sorteio = 30;
	DESTINOS novaZelandia;
		novaZelandia.nome = "Nova Zelândia";
		novaZelandia.localizacao_x = 1725;
		novaZelandia.localizacao_y = 970;
		novaZelandia.dificuldade = 1;
		novaZelandia.sorteio = 31;
	DESTINOS arabiaSaudita;
		arabiaSaudita.nome = "Arábia Saudita";
		arabiaSaudita.localizacao_x = 1104;
		arabiaSaudita.localizacao_y = 510;
		arabiaSaudita.dificuldade = 1;
		arabiaSaudita.sorteio = 32;
	DESTINOS bangladesh;
		bangladesh.nome = "Bangladesh";
		bangladesh.localizacao_x = 1331;
		bangladesh.localizacao_y = 501;
		bangladesh.dificuldade = 1;
		bangladesh.sorteio = 33;
	DESTINOS coreiaNorte;
		coreiaNorte.nome = "Coréia do Norte";
		coreiaNorte.localizacao_x = 1483;
		coreiaNorte.localizacao_y = 370;
		coreiaNorte.dificuldade = 1;
		coreiaNorte.sorteio = 34;
	DESTINOS coreiaSul;
		coreiaSul.nome = "Coréia do Sul";
		coreiaSul.localizacao_x = 1494;
		coreiaSul.localizacao_y = 389;
		coreiaSul.dificuldade = 1;
		coreiaSul.sorteio = 35;
	DESTINOS indonesia;
		indonesia.nome = "Indonésia";
		indonesia.localizacao_x = 1430;
		indonesia.localizacao_y = 681;
		indonesia.dificuldade = 1;
		indonesia.sorteio = 36;
	DESTINOS india;
		india.nome = "Índia";
		india.localizacao_x = 1249;
		india.localizacao_y = 480;
		india.dificuldade = 1;
		india.sorteio = 37;
	DESTINOS ira;
		ira.nome = "Irã";
		ira.localizacao_x = 1120;
		ira.localizacao_y = 434;
		ira.dificuldade = 1;
		ira.sorteio = 38;
	DESTINOS iraque;
		iraque.nome = "Iraque";
		iraque.localizacao_x = 1083;
		iraque.localizacao_y = 454;
		iraque.dificuldade = 1;
		iraque.sorteio = 39;
	DESTINOS japao;
		japao.nome = "Japão";
		japao.localizacao_x = 1558;
		japao.localizacao_y = 393;
		japao.dificuldade = 1;
		japao.sorteio = 40;
	DESTINOS paquistao;
		paquistao.nome = "Paquistão";
		paquistao.localizacao_x = 1229;
		paquistao.localizacao_y = 441;
		paquistao.dificuldade = 1;
		paquistao.sorteio = 41;
	DESTINOS russia;
		russia.nome = "Rússia";
		russia.localizacao_x = 1014;
		russia.localizacao_y = 285;
		russia.dificuldade = 1;
		russia.sorteio = 42;
	DESTINOS tailandia;
		tailandia.nome = "Tailândia";
		tailandia.localizacao_x = 1392;
		tailandia.localizacao_y = 551;
		tailandia.dificuldade = 1;
		tailandia.sorteio = 43;
	DESTINOS turquia;
		turquia.nome = "Turquia";
		turquia.localizacao_x = 1016;
		turquia.localizacao_y = 405;
		turquia.dificuldade = 1;
		turquia.sorteio = 44;
	DESTINOS uzbequistao;
		uzbequistao.nome = "Uzbequistão";
		uzbequistao.localizacao_x = 1181;
		uzbequistao.localizacao_y = 395;
		uzbequistao.dificuldade = 1;
		uzbequistao.sorteio = 45;
	DESTINOS vietna;
		vietna.nome = "Vietnã";
		vietna.localizacao_x = 1415;
		vietna.localizacao_y = 505;
		vietna.dificuldade = 1;
		vietna.sorteio = 46;
	DESTINOS alemanha;
		alemanha.nome = "Alemanha";
		alemanha.localizacao_x = 919;
		alemanha.localizacao_y = 325;
		alemanha.dificuldade = 1;
		alemanha.sorteio = 47;
	DESTINOS austria;
		austria.nome = "Áustria";
		austria.localizacao_x = 933;
		austria.localizacao_y = 357;
		austria.dificuldade = 1;
		austria.sorteio = 48;
	DESTINOS dinamarca;
		dinamarca.nome = "Dinamarca";
		dinamarca.localizacao_x = 911;
		dinamarca.localizacao_y = 304;
		dinamarca.dificuldade = 1;
		dinamarca.sorteio = 49;
	DESTINOS espanha;
		espanha.nome = "Espanha";
		espanha.localizacao_x = 842;
		espanha.localizacao_y = 410;
		espanha.dificuldade = 1;
		espanha.sorteio = 50;
	DESTINOS finlandia;
		finlandia.nome = "Finlândia";
		finlandia.localizacao_x = 966;
		finlandia.localizacao_y = 259;
		finlandia.dificuldade = 1;
		finlandia.sorteio = 51;
	DESTINOS franca;
		franca.nome = "França";
		franca.localizacao_x = 876;
		franca.localizacao_y = 355;
		franca.dificuldade = 1;
		franca.sorteio = 52;
	DESTINOS grecia;
		grecia.nome = "Grécia";
		grecia.localizacao_x = 974;
		grecia.localizacao_y = 421;
		grecia.dificuldade = 1;
		grecia.sorteio = 53;
	DESTINOS italia;
		italia.nome = "Itália";
		italia.localizacao_x = 924;
		italia.localizacao_y = 401;
		italia.dificuldade = 1;
		italia.sorteio = 54;
	DESTINOS noruega;
		noruega.nome = "Noruega";
		noruega.localizacao_x = 901;
		noruega.localizacao_y = 272;
		noruega.dificuldade = 1;
		noruega.sorteio = 55;
	DESTINOS holanda;
		holanda.nome = "Holanda";
		holanda.localizacao_x = 880;
		holanda.localizacao_x = 326;
		holanda.dificuldade = 1;
		holanda.sorteio = 56;
	DESTINOS polonia;
		polonia.nome = "Polônia";
		polonia.localizacao_x = 963;
		polonia.localizacao_y = 327;
		polonia.dificuldade = 1;
		polonia.sorteio = 57;
	DESTINOS portugal;
		portugal.nome = "Portugal";
		portugal.localizacao_x = 813;
		portugal.localizacao_y = 422;
		portugal.dificuldade = 1;
		portugal.sorteio = 58;
	DESTINOS inglaterra;
		inglaterra.nome = "Inglaterra";
		inglaterra.localizacao_x = 861;
		inglaterra.localizacao_y = 331;
		inglaterra.dificuldade = 1;
		inglaterra.sorteio = 59;
	DESTINOS suecia;
		suecia.nome = "Suécia";
		suecia.localizacao_x = 939;
		suecia.localizacao_y = 267;
		suecia.dificuldade = 1;
		suecia.sorteio = 60;

	//Dificuldade 2
	DESTINOS bahamas;
		bahamas.nome = "Bahamas";
		bahamas.localizacao_x = 452;
		bahamas.localizacao_y = 495;
		bahamas.dificuldade = 2;
		bahamas.sorteio = 1;
	DESTINOS elSalvador;
		elSalvador.nome = "El Salvador";
		elSalvador.localizacao_x = 387;
		elSalvador.localizacao_y = 558;
		elSalvador.dificuldade = 2;
		elSalvador.sorteio = 2;
	DESTINOS guatemala;
		guatemala.nome = "Guatemala";
		guatemala.localizacao_x = 380;
		guatemala.localizacao_y = 549;
		guatemala.dificuldade = 2;
		guatemala.sorteio = 3;
	DESTINOS nicaragua;
		nicaragua.nome = "Nicarágua";
		nicaragua.localizacao_x = 400;
		nicaragua.localizacao_y = 567;
		nicaragua.dificuldade = 2;
		nicaragua.sorteio = 4;
	DESTINOS panama;
		panama.nome = "Panamá";
		panama.localizacao_x = 419;
		panama.localizacao_y = 591;
		panama.dificuldade = 2;
		panama.sorteio = 5;
	DESTINOS guiana;
		guiana.nome = "Guiana";
		guiana.localizacao_x = 544;
		guiana.localizacao_y = 605;
		guiana.dificuldade = 2;
		guiana.sorteio = 6;
	DESTINOS suriname;
		suriname.nome = "Suriname";
		suriname.localizacao_x = 561;
		suriname.localizacao_y = 612;
		suriname.dificuldade = 2;
		suriname.sorteio = 7;
	DESTINOS angola;
		angola.nome = "Angola";
		angola.localizacao_x = 932;
		angola.localizacao_y = 692;
		angola.dificuldade = 2;
		angola.sorteio = 8;
	DESTINOS caboVerde;
		caboVerde.nome = "Cabo Verde";
		caboVerde.localizacao_x = 738;
		caboVerde.localizacao_y = 563;
		caboVerde.dificuldade = 2;
		caboVerde.sorteio = 9;
	DESTINOS etiopia;
		etiopia.nome = "Etiópia";
		etiopia.localizacao_x = 1059; 
		etiopia.localizacao_y = 590;
		etiopia.dificuldade = 2;
		etiopia.sorteio = 10;
	DESTINOS guine;
		guine.nome = "Guiné";
		guine.localizacao_x = 782;
		guine.localizacao_y = 588;
		guine.dificuldade = 2;
		guine.sorteio = 11;
	DESTINOS guineBissau;
		guineBissau.nome = "Guiné-Bissau";
		guineBissau.localizacao_x = 776;
		guineBissau.localizacao_y = 575;
		guineBissau.dificuldade = 2;
		guineBissau.sorteio = 12;
	DESTINOS guineEquatorial;
		guineEquatorial.nome = "Guiné Equatorial";
		guineEquatorial.localizacao_x = 905;
		guineEquatorial.localizacao_y = 623;
		guineEquatorial.dificuldade = 2;
		guineEquatorial.sorteio = 13;
	DESTINOS lesoto;
		lesoto.nome = "Lesoto";
		lesoto.localizacao_x = 1004;
		lesoto.localizacao_y = 807;
		lesoto.dificuldade = 2;
		lesoto.sorteio = 14;
	DESTINOS mauritania;
		mauritania.nome = "Mauritânia";
		mauritania.localizacao_x = 772;
		mauritania.localizacao_y = 539;
		mauritania.dificuldade = 2;
		mauritania.sorteio = 15;
	DESTINOS niger;
		niger.nome = "Níger";
		niger.localizacao_x = 876;
		niger.localizacao_y = 562;
		niger.dificuldade = 2;
		niger.sorteio = 16;
	DESTINOS quenia;
		quenia.nome = "Quênia";
		quenia.localizacao_x = 1060;
		quenia.localizacao_y = 644;
		quenia.dificuldade = 2;
		quenia.sorteio = 17;
	DESTINOS republicaCongo;
		republicaCongo.nome = "República do Congo";
		republicaCongo.localizacao_x = 939;
		republicaCongo.localizacao_y = 660;
		republicaCongo.dificuldade = 2;
		republicaCongo.sorteio = 18;
	DESTINOS saoTomePrincipe;
		saoTomePrincipe.nome = "São Tomé e Príncipe";
		saoTomePrincipe.localizacao_x = 898;
		saoTomePrincipe.localizacao_y = 634;
		saoTomePrincipe.dificuldade = 2;
		saoTomePrincipe.sorteio = 20;
	DESTINOS sudao;
		sudao.nome = "Sudão";
		sudao.localizacao_x = 1032;
		sudao.localizacao_y = 547;
		sudao.dificuldade = 2;
		sudao.sorteio = 21;
	DESTINOS sudaoSul;
		sudaoSul.nome = "Sudão do Sul";
		sudaoSul.localizacao_x = 1027;
		sudaoSul.localizacao_y = 604;
		sudaoSul.dificuldade = 2;
		sudaoSul.sorteio = 22;
	DESTINOS tanzania;
		tanzania.nome = "Tanzânia";
		tanzania.localizacao_x = 1069;
		tanzania.localizacao_y = 684;
		tanzania.dificuldade = 2;
		tanzania.sorteio = 23;
	DESTINOS togo;
		togo.nome = "Togo";
		togo.localizacao_x = 865;
		togo.localizacao_y = 605;
		togo.dificuldade = 2;
		togo.sorteio = 24;
	DESTINOS zambia;
		zambia.nome = "Zâmbia";
		zambia.localizacao_x = 1002;
		zambia.localizacao_y = 725;
		zambia.dificuldade = 2;
		zambia.sorteio = 25;
	DESTINOS zimbabwe;
		zimbabwe.nome = "Zimbabwe";
		zimbabwe.localizacao_x = 1017;
		zimbabwe.localizacao_y = 742;
		zimbabwe.dificuldade = 2;
		zimbabwe.sorteio = 26;
	DESTINOS papuaNovaGuine;
		papuaNovaGuine.nome = "Papua-Nova Guiné";
		papuaNovaGuine.localizacao_x = 1648;
		papuaNovaGuine.localizacao_y = 714;
		papuaNovaGuine.dificuldade = 2;
		papuaNovaGuine.sorteio = 27;
	DESTINOS oma;
		oma.nome = "Omã";
		oma.localizacao_x = 1167;
		oma.localizacao_y = 508;
		oma.dificuldade = 2;
		oma.sorteio = 28;
	DESTINOS afeganistao;
		afeganistao.nome = "Afeganistão";
		afeganistao.localizacao_x = 1206;
		afeganistao.localizacao_y = 440;
		afeganistao.dificuldade = 2;
		afeganistao.sorteio = 29;
	DESTINOS azerbaijao;
		azerbaijao.nome = "Azerbaijão";
		azerbaijao.localizacao_x = 1101;
		azerbaijao.localizacao_y = 401;
		azerbaijao.dificuldade = 2;
		azerbaijao.sorteio = 30;
	DESTINOS camboja;
		camboja.nome = "Camboja";
		camboja.localizacao_x = 1416;
		camboja.localizacao_y = 564;
		camboja.dificuldade = 2;
		camboja.sorteio = 31;
	DESTINOS filipinas;
		filipinas.nome = "Filipinas";
		filipinas.localizacao_x = 1505;
		filipinas.localizacao_y = 545;
		filipinas.dificuldade = 2;
		filipinas.sorteio = 32;
	DESTINOS georgia;
		georgia.nome = "Geórgia";
		georgia.localizacao_x = 1061;
		georgia.localizacao_y = 391;
		georgia.dificuldade = 2;
		georgia.sorteio = 33;
	DESTINOS maldivas;
		maldivas.nome = "Maldivas";
		maldivas.localizacao_x = 1251;
		maldivas.localizacao_y = 621;
		maldivas.dificuldade = 2;
		maldivas.sorteio = 34;
	DESTINOS mongolia;
		mongolia.nome = "Mongólia";
		mongolia.localizacao_x = 1374;
		mongolia.localizacao_y = 325;
		mongolia.dificuldade = 2;
		mongolia.sorteio = 35;
	DESTINOS nepal;
		nepal.nome = "Nepal";
		nepal.localizacao_x = 1297;
		nepal.localizacao_y = 468;
		nepal.dificuldade = 2;
		nepal.sorteio = 36;
	DESTINOS quirguistao;
		quirguistao.nome = "Quirguistão";
		quirguistao.localizacao_x = 1224;
		quirguistao.localizacao_y = 379;
		quirguistao.dificuldade = 2;
		quirguistao.sorteio = 37;
	DESTINOS sriLanka;
		sriLanka.nome = "Sri Lanka";
		sriLanka.localizacao_x = 1290;
		sriLanka.localizacao_y = 594;
		sriLanka.dificuldade = 2;
		sriLanka.sorteio = 38;
	DESTINOS albania;
		albania.nome = "Albânia";
		albania.localizacao_x = 958;
		albania.localizacao_y = 403;
		albania.dificuldade = 2;
		albania.sorteio = 39;
	DESTINOS armenia;
		armenia.nome = "Armênia";
		armenia.localizacao_x = 1078;
		armenia.localizacao_y = 405;
		armenia.dificuldade = 2;
		armenia.sorteio = 40;
	DESTINOS belgica;
		belgica.nome = "Bélgica";
		belgica.localizacao_x = 880;
		belgica.localizacao_y = 336;
		belgica.dificuldade = 2;
		belgica.sorteio = 42;
	DESTINOS bulgaria;
		bulgaria.nome = "Bulgária";
		bulgaria.localizacao_x = 972;
		bulgaria.localizacao_y = 390;
		bulgaria.dificuldade = 2;
		bulgaria.sorteio = 43;
	DESTINOS cazaquistao;
		cazaquistao.nome = "Cazaquistão";
		cazaquistao.localizacao_x = 1208;
		cazaquistao.localizacao_y = 327;
		cazaquistao.dificuldade = 2;
		cazaquistao.sorteio = 44;
	DESTINOS republicaTcheca;
		republicaTcheca.nome = "República Tcheca";
		republicaTcheca.localizacao_x = 929;
		republicaTcheca.localizacao_y = 342;
		republicaTcheca.dificuldade = 2;
		republicaTcheca.sorteio = 45;
	DESTINOS croacia;
		croacia.nome = "Croácia";
		croacia.localizacao_x = 934;
		croacia.localizacao_y = 379;
		croacia.dificuldade = 2;
		croacia.sorteio = 46;
	DESTINOS eslovaquia;
		eslovaquia.nome = "Eslováquia";
		eslovaquia.localizacao_x = 948;
		eslovaquia.localizacao_y = 352;
		eslovaquia.dificuldade = 2;
		eslovaquia.sorteio = 47;
	DESTINOS eslovenia;
		eslovenia.nome = "Eslovênia";
		eslovenia.localizacao_x = 928;
		eslovenia.localizacao_y = 369;
		eslovenia.dificuldade = 2;
		eslovenia.sorteio = 48;
	DESTINOS hungria;
		hungria.nome = "Hungria";
		hungria.localizacao_x = 954;
		hungria.localizacao_y = 363;
		hungria.dificuldade = 2;
		hungria.sorteio = 49;
	DESTINOS irlanda;
		irlanda.nome = "Irlanda";
		irlanda.localizacao_x = 827;
		irlanda.localizacao_y = 323;
		irlanda.dificuldade = 2;
		irlanda.sorteio = 50;
	DESTINOS islandia;
		islandia.nome = "Islândia";
		islandia.localizacao_x = 777;
		islandia.localizacao_y = 241;
		islandia.dificuldade = 2;
		islandia.sorteio = 51;
	DESTINOS luxemburgo;
		luxemburgo.nome = "Luxemburgo";
		luxemburgo.localizacao_x = 893;
		luxemburgo.localizacao_y = 345;
		luxemburgo.dificuldade = 2;
		luxemburgo.sorteio = 52;
	DESTINOS monaco;
		monaco.nome = "Mônaco";
		monaco.localizacao_x = 896;
		monaco.localizacao_y = 386;
		monaco.dificuldade = 2;
		monaco.sorteio = 53;
	DESTINOS escocia;
		escocia.nome = "Escócia";
		escocia.localizacao_x = 847;
		escocia.localizacao_y = 301;
		escocia.dificuldade = 2;
		escocia.sorteio = 54;
	DESTINOS irlandaNorte;
		irlandaNorte.nome = "Irlanda do Norte";
		irlandaNorte.localizacao_x = 830;
		irlandaNorte.localizacao_y = 310;
		irlandaNorte.dificuldade = 2;
		irlandaNorte.sorteio = 55;
	DESTINOS servia;
		servia.nome = "Sérvia";
		servia.localizacao_x = 943;
		servia.localizacao_y = 375;
		servia.dificuldade = 2;
		servia.sorteio = 56;
	DESTINOS suica;
		suica.nome = "Suíça";
		suica.localizacao_x = 895;
		suica.localizacao_y = 362;
		suica.dificuldade = 2;
		suica.sorteio = 57;
	DESTINOS ucrania;
		ucrania.nome = "Ucrânia";
		ucrania.localizacao_x = 1005;
		ucrania.localizacao_y = 333;
		ucrania.dificuldade = 2;
		ucrania.sorteio = 58;
	DESTINOS guianaFrancesa;
		guianaFrancesa.nome = "Guiana Francesa";
		guianaFrancesa.localizacao_x = 579;
		guianaFrancesa.localizacao_y = 615;
		guianaFrancesa.dificuldade = 2;
		guianaFrancesa.sorteio = 59;
	
	//Dificuldade 3
	DESTINOS belize;
		belize.nome = "Belize";
		belize.localizacao_x = 390;
		belize.localizacao_y = 537;	
		belize.dificuldade = 3;
		belize.sorteio = 1;
	DESTINOS argelia;
		argelia.nome = "Argélia";
		argelia.localizacao_x = 876;
		argelia.localizacao_y = 432;
		argelia.dificuldade = 3;
		argelia.sorteio = 2;
	DESTINOS benim;
		benim.nome = "Benim";
		benim.localizacao_x = 871;
		benim.localizacao_y = 600;
		benim.dificuldade = 3;
		benim.sorteio = 3;
	DESTINOS botswana;
		botswana.nome = "Botswana";
		botswana.localizacao_x = 991;
		botswana.localizacao_y = 773;
		botswana.dificuldade = 3;
		botswana.sorteio = 4;
	DESTINOS burkinaFaso;
		burkinaFaso.nome = "Burkina Faso";
		burkinaFaso.localizacao_x = 852;
		burkinaFaso.localizacao_y = 571;
		burkinaFaso.dificuldade = 3;
		burkinaFaso.sorteio = 5;
	DESTINOS burundi;
		burundi.nome = "Burundi";
		burundi.localizacao_x = 1018;
		burundi.localizacao_y = 659;
		burundi.dificuldade = 3;
		burundi.sorteio = 6;
	DESTINOS chade;
		chade.nome = "Chade";
		chade.localizacao_x = 943;
		chade.localizacao_y = 579;
		chade.dificuldade = 3;
		chade.sorteio = 7;
	DESTINOS comores;
		comores.nome = "Comores";
		comores.localizacao_x = 1098;
		comores.localizacao_y = 704;
		comores.dificuldade = 3;
		comores.sorteio = 8;
	DESTINOS djibouti;
		djibouti.nome = "Djibouti";
		djibouti.localizacao_x = 1087;
		djibouti.localizacao_y = 572;
		djibouti.dificuldade = 3;
		djibouti.sorteio = 9;
	DESTINOS eritreia;
		eritreia.nome = "Eritreia";
		eritreia.localizacao_x = 1064;
		eritreia.localizacao_y = 552;
		eritreia.dificuldade = 3;
		eritreia.sorteio = 10;
	DESTINOS gabao;
		gabao.nome = "Gabão";
		gabao.localizacao_x = 910;
		gabao.localizacao_y = 641;
		gabao.dificuldade = 3;
		gabao.sorteio = 11;
	DESTINOS gambia;
		gambia.nome = "Gâmbia";
		gambia.localizacao_x = 774;
		gambia.localizacao_y = 566;
		gambia.dificuldade = 3;
		gambia.sorteio = 12;
	DESTINOS liberia;
		liberia.nome = "Libéria";
		liberia.localizacao_x = 800;
		liberia.localizacao_y = 607;
		liberia.dificuldade = 3;
		liberia.sorteio = 13;
	DESTINOS malawi;
		malawi.nome = "Malawi";
		malawi.localizacao_x = 1042;
		malawi.localizacao_y = 707;
		malawi.dificuldade = 3;
		malawi.sorteio = 14;
	DESTINOS mali;
		mali.nome = "Mali";
		mali.localizacao_x = 819;
		mali.localizacao_y = 567;
		mali.dificuldade = 3;
		mali.sorteio = 15;
	DESTINOS mauricia;
		mauricia.nome = "Maurícia";
		mauricia.localizacao_x = 1162;
		mauricia.localizacao_y = 760;
		mauricia.dificuldade = 3;
		mauricia.sorteio = 16;
	DESTINOS namibia;
		namibia.nome = "Namíbia";
		namibia.localizacao_x = 946;
		namibia.localizacao_y = 775;
		namibia.dificuldade = 3;
		namibia.sorteio = 17;
	DESTINOS republicaCentroAfricana;
		republicaCentroAfricana.nome = "República Centro-Africana";
		republicaCentroAfricana.localizacao_x = 956;
		republicaCentroAfricana.localizacao_y = 613;
		republicaCentroAfricana.dificuldade = 3;
		republicaCentroAfricana.sorteio = 18;
	DESTINOS ruanda;
		ruanda.nome = "Ruanda";
		ruanda.localizacao_x = 1020;
		ruanda.localizacao_y = 650;
		ruanda.dificuldade = 3;
		ruanda.sorteio = 19;
	DESTINOS serraLeoa;
		serraLeoa.nome = "Serra Leoa";
		serraLeoa.localizacao_x = 789;
		serraLeoa.localizacao_y = 595;
		serraLeoa.dificuldade = 3;
		serraLeoa.sorteio = 20;
	DESTINOS seychelles;
		seychelles.nome = "Seychelles";
		seychelles.localizacao_x = 1158;
		seychelles.localizacao_y = 665;
		seychelles.dificuldade = 3;
		seychelles.sorteio = 21;
	DESTINOS suzilandia;
		suzilandia.nome = "Suzilândia";
		suzilandia.localizacao_x = 1023;
		suzilandia.localizacao_y = 789;
		suzilandia.dificuldade = 3;
		suzilandia.sorteio = 22;
	DESTINOS tunisia;
		tunisia.nome = "Tunísia";
		tunisia.localizacao_x = 906;
		tunisia.localizacao_y = 426;
		tunisia.dificuldade = 3;
		tunisia.sorteio = 23;
	DESTINOS uganda;
		uganda.nome = "Uganda";
		uganda.localizacao_x = 1031;
		uganda.localizacao_y = 639;
		uganda.dificuldade = 3;
		uganda.sorteio = 24;
	DESTINOS ilhasSalomao;
		ilhasSalomao.nome = "Ilhas Salomão";
		ilhasSalomao.localizacao_x = 1711;
		ilhasSalomao.localizacao_y = 703;
		ilhasSalomao.dificuldade = 3;
		ilhasSalomao.sorteio = 25;
	DESTINOS bahrein;
		bahrein.nome = "Bahrein";
		bahrein.localizacao_x = 1115;
		bahrein.localizacao_y = 483;
		bahrein.dificuldade = 3;
		bahrein.sorteio = 26;
	DESTINOS brunei;
		brunei.nome = "Brunei";
		brunei.localizacao_x = 1472;
		brunei.localizacao_y = 611;
		brunei.dificuldade = 3;
		brunei.sorteio = 27;
	DESTINOS butao;
		butao.nome = "Butão";
		butao.localizacao_x = 1324;
		butao.localizacao_y = 470;
		butao.dificuldade = 3;
		butao.sorteio = 28;
	DESTINOS chipre;
		chipre.nome = "Chipre";
		chipre.localizacao_x = 1024;
		chipre.localizacao_y = 441;
		chipre.dificuldade = 3;
		chipre.sorteio = 29;
	DESTINOS laos;
		laos.nome = "Laos";
		laos.localizacao_x = 1397;
		laos.localizacao_y = 522;
		laos.dificuldade = 3;
		laos.sorteio = 30;
	DESTINOS tajiquistao;
		tajiquistao.nome = "Tajiquistão";
		tajiquistao.localizacao_x = 1202;
		tajiquistao.localizacao_y = 405;
		tajiquistao.dificuldade = 3;
		tajiquistao.sorteio = 31;
	DESTINOS timorLeste;
		timorLeste.nome = "Timor-Leste";
		timorLeste.localizacao_x = 1502;
		timorLeste.localizacao_y = 698;
		timorLeste.dificuldade = 3;
		timorLeste.sorteio = 32;
	DESTINOS turquemenistao;
		turquemenistao.nome = "Turquemenistao";
		turquemenistao.localizacao_x = 1166;
		turquemenistao.localizacao_y = 416;
		turquemenistao.dificuldade = 3;
		turquemenistao.sorteio = 33;
	DESTINOS andorra;
		andorra.nome = "Andorra";
		andorra.localizacao_x = 868;
		andorra.localizacao_y = 392;
		andorra.dificuldade = 3;
		andorra.sorteio = 34;
	DESTINOS bielorrusia;
		bielorrusia.nome = "Bielorrúsia";
		bielorrusia.localizacao_x = 991;
		bielorrusia.localizacao_y = 315;
		bielorrusia.dificuldade = 3;
		bielorrusia.sorteio = 35;
	DESTINOS bosniaHerzegovinia;
		bosniaHerzegovinia.nome = "Bósnia e Herzegovinia";
		bosniaHerzegovinia.localizacao_x = 949;
		bosniaHerzegovinia.localizacao_y = 384;
		bosniaHerzegovinia.dificuldade = 3;
		bosniaHerzegovinia.sorteio = 36;
	DESTINOS estonia;
		estonia.nome = "Estônia";
		estonia.localizacao_x = 970;
		estonia.localizacao_y = 273;
		estonia.dificuldade = 3;
		estonia.sorteio = 37;
	DESTINOS kosovo;
		kosovo.nome = "Kosovo";
		kosovo.localizacao_x = 963;
		kosovo.localizacao_y = 390;
		kosovo.dificuldade = 3;
		kosovo.sorteio = 38;
	DESTINOS letonia;
		letonia.nome = "Letônia";
		letonia.localizacao_x = 973;
		letonia.localizacao_y = 288;
		letonia.dificuldade = 3;
		letonia.sorteio = 39;
	DESTINOS liechtenstein;
		liechtenstein.nome = "Liechtenstein";
		liechtenstein.localizacao_x = 913;
		liechtenstein.localizacao_y = 360;
		liechtenstein.dificuldade = 3;
		liechtenstein.sorteio = 40;
	DESTINOS lituania;
		lituania.nome = "Lituânia";
		lituania.localizacao_x = 974;
		lituania.localizacao_y = 303;
		lituania.dificuldade = 3;
		lituania.sorteio = 41;
	DESTINOS malta;
		malta.nome = "Malta";
		malta.localizacao_x = 932;
		malta.localizacao_y = 438;
		malta.dificuldade = 3;
		malta.sorteio = 42;
	DESTINOS moldavia;
		moldavia.nome = "Moldávia";
		moldavia.localizacao_x = 994;
		moldavia.localizacao_y = 361;
		moldavia.dificuldade = 3;
		moldavia.sorteio = 43;
	DESTINOS montenegro;
		montenegro.nome = "Montenegro";
		montenegro.localizacao_x = 953;
		montenegro.localizacao_y = 392;
		montenegro.dificuldade = 3;
		montenegro.dificuldade = 44;
	DESTINOS paisGales;
		paisGales.nome = "País de Gales";
		paisGales.localizacao_x = 845;
		paisGales.localizacao_y = 333;
		paisGales.dificuldade = 3;
		paisGales.sorteio = 45;
	DESTINOS malasia;
		malasia.nome = "Macedônia";
		malasia.localizacao_x = 1400;
		malasia.localizacao_y = 620;
		malasia.dificuldade = 3;
		malasia.sorteio = 46;
	DESTINOS romenia;
		romenia.nome = "Romênia";
		romenia.localizacao_x = 984;
		romenia.localizacao_y = 377;
		romenia.dificuldade = 3;
		romenia.sorteio = 47;
	DESTINOS sanMarino;
		sanMarino.nome = "San Marino";
		sanMarino.localizacao_x = 917;
		sanMarino.localizacao_y = 381;
		sanMarino.dificuldade = 3;
		sanMarino.sorteio = 48;
}
